google2
```{r}
library(googlesheets)
library(tidyverse)
library(lubridate)
source("fig_save_jpeg.R")
source("summarySE.R")
```
```{r}
e <- gs_key("1Uu6XF0LC4vRN8Vl_7XFfLd7TnjtCfSxI5USe3WaX-Ns")
```

```{r}
e2 <- e %>%
    gs_read_csv(ws="Form Responses 1")
e2 <- e2 %>%
    select(-c(`Time to use`,Perfusion,Pulse,Files,Date_2,Date_1,Date))
   
col_2_change <- c(7,8,9,11,12,13,14,15,16,18,19,26,30,35,36,38,40,47,49)
e2[col_2_change] <- lapply(e2[col_2_change], as.factor)
col_2_change <- c(25,27,29,31,46)
e2[col_2_change] <- lapply(e2[col_2_change], as.numeric)
e2$Timestamp <-mdy_hms(e2$Timestamp, tz="America/Chicago")
e2$ts_date <- date(e2$Timestamp) 
e2 <- e2 %>%
    mutate(alt.ts=ifelse(!is.na(`Time (if data collected earlier)`),paste(ts_date,`Time (if data collected earlier)`, sep=" "),NA))
e2$alt.ts <- ymd_hms(e2$alt.ts,tz="America/Chicago")
e2 <- e2 %>%
    mutate(ts.use=pmin(Timestamp,alt.ts,na.rm = TRUE))

vital_data <- e2 %>%
    select(ts.use,`Weight (lbs)`,`Systolic (mmHg)`,`Diastolic (mmHg)`,`Heart Rate (bmp)`,`Overnight heart rate (bpm)`,`Overnight O2 Sat.`,`Overnight Heart Rate Alarm`,Glucose, `Temperature f`, `BP method`) 

bp <- vital_data %>%
    filter(!is.na(`Systolic (mmHg)`)&!is.na(`Diastolic (mmHg)`)) %>%
        select(ts.use,`Diastolic (mmHg)`,`Systolic (mmHg)`)
bp2 <- tidyr::gather(data = bp, key = Key, value = mmHg, na.rm = FALSE, `Diastolic (mmHg)`, `Systolic (mmHg)`)


```


```{r}
ggplot(bp2,aes(ts.use,mmHg))+
    geom_point(aes(color=Key))+
    scale_color_discrete(name="Value",
                        breaks=c("Diastolic (mmHg)", "Systolic (mmHg)"),
                    labels=c("Diastolic","Systolic"))+
    labs(title="Ephraim's Blood Pressure",
         x="Date")+
    theme_bw()

```
```{r}
str(bp2)
```

```{r}
bp2 <- bp2 %>%
    mutate(grp=as.factor(if_else(ts.use < '2018-03-15', "Pre admission",
               if_else(ts.use<='2018-04-06'&ts.use>='2018-03-15',"Post admission 3.125 QD",
               if_else(ts.use>'2018-04-06'&ts.use<='2018-04-25',"D/C Carvedilol",
                if_else(ts.use>'2018-04-25'&ts.use<='2018-05-29',"Carvedilol Restart: 3.125 mg QD",
                        if_else(ts.use>'2018-05-29'&ts.use<'2018-06-08',  "Carvedilol 2: 3.125 mg BID",
                                "Carvedilol 3: 3.125 mg BID")))))))
table(bp2$grp)


```

```{r}
## Reordering bp2$grp
bp2$grp <- factor(bp2$grp, levels=c("Pre admission", "Post admission 3.125 QD", "D/C Carvedilol", "Carvedilol Restart: 3.125 mg QD", "Carvedilol 2: 3.125 mg BID", "Carvedilol 3: 3.125 mg BID"))
```

```{r}
ggplot(bp2,aes(ts.use,mmHg))+
    geom_point(aes(color=grp))+
    labs(title="Ephraim's Blood Pressure",
         x="Date")+
    theme_bw()
fig_save_jpeg("current_bp")
```

```{r}
ggplot(bp2, aes(Key,mmHg))+
    geom_boxplot(aes(fill=grp))
fig_save_jpeg("current_box")
```

```{r}
systolic <- bp2 %>%
    filter(Key=="Systolic (mmHg)")

sys_mod <- aov(lm(mmHg~grp,systolic))
TukeyHSD(sys_mod)
```
```{r}
library(broom)
tukey <- tidy(TukeyHSD(sys_mod))
write_csv(tukey,"tukey_data.CSV")
```

```{r}
plot(TukeyHSD(sys_mod))
```

```{r}
sum1 <- summarySE(bp2,measurevar = "mmHg",groupvars = c("Key","grp"))
write_csv(sum1,"sum1.CSV")
```
```{r}
sum2 <- bp2 %>%
    group_by(Key,grp) %>%
        summarize(min_val=min(mmHg),
                  max_val=max(mmHg),
                  mean_val=mean(mmHg),
                  sd_val=sd(mmHg))
write_csv(sum2,"sum2.CSV")
```

```{r}
sum2
```
