```{r}
library(googlesheets)
library(tidyverse)
library(lubridate)
```
```{r}
e <- gs_key("1Uu6XF0LC4vRN8Vl_7XFfLd7TnjtCfSxI5USe3WaX-Ns")
```
 
```{r eval=FALSE, include=FALSE}

edata <- e %>%
    gs_read(ws="Form Responses 1",   Date_2 = col_skip(), Files = col_skip(), 
        `IO Cath Time` = col_time(format = "%H:%M"), 
        Perfusion = col_skip(), Pulse = col_skip(), 
        `Time (if data collected earlier)` = col_time(format = "%H:%M"), 
        `Time Ephraim becomes responsive?` = col_time(format = "%H:%M"), 
        `Time Event Started` = col_time(format = "%H:%M"), 
        `Time Overnight cath in` = col_time(format = "%H:%M"), 
        `Time fluids started` = col_time(format = "%H:%M"), 
        `Time fluids stopped` = col_time(format = "%H:%M"), 
        `Time he fell asleep` = col_time(format = "%H:%M"), 
        `Time he got out of bed` = col_time(format = "%H:%M"), 
        `Time he returns to baseline` = col_time(format = "%H:%M"), 
        `Time he woke up` = col_time(format = "%H:%M"), 
        `Time overnight cath out` = col_time(format = "%H:%M"), 
        `Time placed in bed` = col_time(format = "%H:%M"), 
        `Time to use` = col_skip(), Timestamp = col_datetime(format = "%m/%d/%Y %H:%M"), 
        `Wet diaper between cath time` = col_time(format = "%H:%M"))
```
 

```{r}
e2 <- e %>%
    gs_read_csv(ws="Form Responses 1")
e2 <- e2 %>%
    select(-c(`Time to use`,Perfusion,Pulse,Files,Date_2,Date_1,Date))
    
```
```{r}
e2$Timestamp <- mdy_hms(e2$Timestamp, tz="America/Chicago")
```

```{r}
str(e2, give.attr=FALSE)
```
 
```{r}
e2 <- e2 %>%
    mutate(ts_date=date(Timestamp))
```
```{r}

head(e2$ts_date)

```
```{r}
e2 <- e2 %>%
    mutate(alt.ts=ifelse(!is.na(`Time (if data collected earlier)`),paste0(ts_date,`Time (if data collected earlier)`),NA))

```
```{r}
head(e2$alt.ts)
```

```{r}
ggplot(e2,aes(lubridate::date(Timestamp),`Weight (lbs)`))+
    geom_point(na.rm = TRUE)+
    labs(x="Date")+
    theme_bw()
```
```{r}
ggplot(e2,aes(Timestamp,`Systolic (mmHg)`))+
    geom_point(na.rm = TRUE)
```
```{r}
#ggplot(e2,aes(`Systolic (mmHg)`))+
```
 
 Neuro events
 timestamps only (TZ and time need to be verify)
```{r}
length(na.omit(e2$`Time Event Started`))
na.omit(e2$`Time Event Started`)
```

Observations
```{r}
day2 <- date(e2$Timestamp)
unique(day2)
length(unique(day2))
```



 