col_types = cols(Date = col_date(format = "%m/%d/%Y"), 
                 Date_1 = col_date(format = "%m/%d/%Y"), 
                 `IO Cath Time` = col_time(format = "%H:%M"), 
                 Perfusion = col_skip(), Pulse = col_skip(), 
                 `Time (if data collected earlier)` = col_time(format = "%H:%M"), 
                 `Time Ephraim becomes responsive?` = col_time(format = "%H:%M"), 
                 `Time Event Started` = col_time(format = "%H:%M"), 
                 `Time Overnight cath in` = col_time(format = "%H:%M"), 
                 `Time fluids started` = col_time(format = "%H:%M"), 
                 `Time fluids stopped` = col_time(format = "%H:%M"), 
                 `Time he fell asleep` = col_time(format = "%H:%M"), 
                 `Time he got out of bed` = col_time(format = "%H:%M"), 
                 `Time he returns to baseline` = col_time(format = "%H:%M"), 
                 `Time he woke up` = col_time(format = "%H:%M"), 
                 `Time overnight cath out` = col_time(format = "%H:%M"), 
                 `Time placed in bed` = col_time(format = "%H:%M"), 
                 `Time to use` = col_skip(), Timestamp = col_datetime(format = "%m/%d/%Y %H:%M"), 
                 `Wet diaper between cath time` = col_time(format = "%H:%M"), 
                 `Wet diaper between cath weight` = col_number())